version: '3.4'

services:
  clientes.db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password@1234
  clientes.api:
    image: ${DOCKER_REGISTRY-}clientesapi
    build:
      context: .
      dockerfile: src/Clientes.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - DB_SERVER=sql_server2022
      - DB_NAME=Clientes
      - DB_PASSWORD=password@1234